import {config} from "./config.js";
type MailPatch=Record<string,unknown>;
const url=()=>config.supabaseUrl.replace(/\/$/,"")+"/rest/v1/mail_messages";
const headers=()=>({apikey:config.supabaseKey,Authorization:"Bearer "+config.supabaseKey,"Content-Type":"application/json","Prefer":"return=minimal"});
async function request(path:string,init:RequestInit){if(!config.supabaseUrl||!config.supabaseKey)throw new Error("mail_database_not_configured");const res=await fetch(url()+path,{...init,headers:{...headers(),...(init.headers??{})}});const body=await res.text();if(!res.ok)throw new Error("mail_database_"+res.status+":"+body.slice(0,500));return body;}
export async function findByIdempotency(key:string){const body=await request("?select=id,status&limit=1&idempotency_key=eq."+encodeURIComponent(key),{method:"GET"});const rows=JSON.parse(body) as Array<{id:string;status:string}>;return rows[0]??null;}
export async function createMessage(m:{id:string;from:string;to:string[];cc?:string[];bcc?:string[];replyTo?:string[];subject:string;html?:string;text?:string;headers?:Record<string,string>;idempotencyKey?:string}){const now=new Date().toISOString();await request("",{method:"POST",body:JSON.stringify({id:m.id,from_address:m.from,to_addresses:m.to,cc_addresses:m.cc??[],bcc_addresses:m.bcc??[],reply_to_addresses:m.replyTo??[],subject:m.subject,html:m.html??null,text:m.text??null,headers:m.headers??{},idempotency_key:m.idempotencyKey??null,status:"queued",attempts:0,next_attempt_at:now,created_at:now,updated_at:now})});}
export async function markSending(id:string,attempts:number){await request("?id=eq."+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({status:"sending",attempts,updated_at:new Date().toISOString()})});}
export async function markSent(id:string,messageId:string){await request("?id=eq."+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({status:"sent",sent_at:new Date().toISOString(),message_id:messageId,last_error:null,updated_at:new Date().toISOString()})});}
export async function markRetry(id:string,attempts:number,error:string,delayMs:number){await request("?id=eq."+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({status:attempts>=config.maxAttempts?"failed":"retry",attempts,next_attempt_at:new Date(Date.now()+delayMs).toISOString(),last_error:error.slice(0,2000),updated_at:new Date().toISOString()})});}