import {createHash,createSign,randomUUID} from "node:crypto";import {resolveMx} from "node:dns/promises";import net from "node:net";import tls from "node:tls";import {config} from "./config.js";import type {MailRecord} from "./types.js";
type Sock=net.Socket|tls.TLSSocket;
const addr=(v:string)=>{const m=v.match(/<([^>]+)>/)??v.match(/([\\w.+-]+@[\\w.-]+)/);if(!m)throw new Error("INVALID_EMAIL");return m[1]};
const domain=(v:string)=>addr(v).split("@").pop()!.toLowerCase();const clean=(v:string)=>v.replace(/[\\r\\n]+/g," ").trim();
const read=(s:Sock)=>new Promise<string>((resolve,reject)=>{let b="";const timer=setTimeout(()=>{cleanup();reject(new Error("SMTP_TIMEOUT"))},config.smtpTimeoutMs);const on=(d:Buffer)=>{b+=d.toString();const lines=b.split("\\r\\n");for(const line of lines){if(/^\\d{3} /.test(line)){cleanup();resolve(line);return}}};const err=(e:Error)=>{cleanup();reject(e)};const cleanup=()=>{clearTimeout(timer);s.off("data",on);s.off("error",err)};s.on("data",on);s.on("error",err)});
async function cmd(s:Sock,c:string,codes:number[]){s.write(c+"\\r\\n");const r=await read(s);if(!codes.includes(Number(r.slice(0,3))))throw new Error("SMTP_"+r);}
async function connect(host:string){return await new Promise<net.Socket>((resolve,reject)=>{const s=net.connect(25,host,()=>resolve(s));const timer=setTimeout(()=>{s.destroy();reject(new Error("SMTP_CONNECT_TIMEOUT"))},config.smtpTimeoutMs);s.once("connect",()=>clearTimeout(timer));s.once("error",reject)})}
async function startTls(s:net.Socket){await cmd(s,"STARTTLS",[220]);return await new Promise<tls.TLSSocket>((resolve,reject)=>{const t=tls.connect({socket:s,servername:config.heloName,rejectUnauthorized:true},()=>resolve(t));t.once("error",reject)})}
function body(m:MailRecord){if(!m.html_body)return ["Content-Type: text/plain; charset=UTF-8","Content-Transfer-Encoding: 8bit","",m.text_body??""].join("\\r\\n");const b="=_Testagram_"+randomUUID().replaceAll("-","");return ["MIME-Version: 1.0",`Content-Type: multipart/alternative; boundary="${b}"`,"",`--${b}`,"Content-Type: text/plain; charset=UTF-8","Content-Transfer-Encoding: 8bit","",m.text_body??"",`--${b}`,"Content-Type: text/html; charset=UTF-8","Content-Transfer-Encoding: 8bit","",m.html_body,`--${b}--`].join("\\r\\n");}
function dkim(m:MailRecord,b:string,from:string,to:string,date:string,id:string){if(!config.dkimPrivateKey)return null;const canonical=b.replace(/\\r?\\n/g,"\\r\\n").replace(/(?:\\r\\n)*$/,"")+"\\r\\n";const bh=createHash("sha256").update(canonical).digest("base64");const value=`v=1; a=rsa-sha256; c=relaxed/simple; d=${config.mailDomain}; s=${config.dkimSelector}; h=from:to:subject:date:message-id; bh=${bh}; b=`;const hs=[["from",from],["to",to],["subject",m.subject],["date",date],["message-id",id]].map(([k,v])=>k+":"+clean(v)).join("\\r\\n");const signer=createSign("RSA-SHA256");signer.update(hs+"\\r\\ndkim-signature:"+value);return "DKIM-Signature: "+value+signer.sign(config.dkimPrivateKey,"base64");}
export async function deliver(m:MailRecord){const from=addr(m.from_address);const groups=new Map<string,string[]>();for(const x of m.to_addresses){const to=addr(x),d=domain(to);groups.set(d,[...(groups.get(d)??[]),to]);}for(const [d,recips] of groups){const mx=(await resolveMx(d)).sort((a,b)=>a.priority-b.priority);if(!mx.length)throw new Error("NO_MX_"+d);let sent=false,last="SMTP_FAILED";for(const r of mx){let s:Sock|null=null;try{const raw=await connect(r.exchange);s=raw;await read(s);await cmd(s,"EHLO "+config.heloName,[250]);if(config.dkimPrivateKey){/* signing is applied below; SMTP TLS is still opportunistic */}await cmd(s,"MAIL FROM:<"+from+">",[250]);for(const to of recips)await cmd(s,"RCPT TO:<"+to+">",[250,251]);const date=new Date().toUTCString(),id="<"+randomUUID()+"@"+config.mailDomain+">",b=body(m),toHead=recips.join(", ");const headers=["From: "+clean(m.from_address),"To: "+clean(toHead),"Subject: "+clean(m.subject),"Date: "+date,"Message-ID: "+id,"MIME-Version: 1.0",m.reply_to?"Reply-To: "+clean(m.reply_to):null,dkim(m,b,m.from_address,toHead,date,id),"X-Mailer: Testagram Mail/1.0"].filter(Boolean).join("\\r\\n");await cmd(s,"DATA",[354]);s.write(headers+"\\r\\n\\r\\n"+b.replace(/^\\./gm,"..")+"\\r\\n.\\r\\n");const ok=await read(s);if(!/^250\\b/.test(ok))throw new Error("SMTP_"+ok);await cmd(s,"QUIT",[221,250]);s.destroy();sent=true;break}catch(e){last=e instanceof Error?e.message:String(e);s?.destroy()}}if(!sent)throw new Error(last);}}
